/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.model;

import org.junit.Test;


/**
 * Model tests for AlertCreateParam
 * 测试变更通知
 */
public class AlertCreateParamTest {
    private final AlertCreateParam model = new AlertCreateParam();

    /**
     * Model tests for AlertCreateParam
     */
    @Test
    public void testAlertCreateParam() {
        // TODO: test AlertCreateParam
    }

    /**
     * Test the property 'alertNotifies'
     */
    @Test
    public void alertNotifiesTest() {
        // TODO: test alertNotifies
    }

    /**
     * Test the property 'alertType'
     */
    @Test
    public void alertTypeTest() {
        // TODO: test alertType
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'notifyRecovered'
     */
    @Test
    public void notifyRecoveredTest() {
        // TODO: test notifyRecovered
    }

    /**
     * Test the property 'recoverNotification'
     */
    @Test
    public void recoverNotificationTest() {
        // TODO: test recoverNotification
    }

    /**
     * Test the property 'tagSet'
     */
    @Test
    public void tagSetTest() {
        // TODO: test tagSet
    }

    /**
     * Test the property 'triggerRule'
     */
    @Test
    public void triggerRuleTest() {
        // TODO: test triggerRule
    }

}
