/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.model;

import org.junit.Test;


/**
 * Model tests for AlertNotifyUpdateParam
 */
public class AlertNotifyUpdateParamTest {
    private final AlertNotifyUpdateParam model = new AlertNotifyUpdateParam();

    /**
     * Model tests for AlertNotifyUpdateParam
     */
    @Test
    public void testAlertNotifyUpdateParam() {
        // TODO: test AlertNotifyUpdateParam
    }

    /**
     * Test the property 'notifyGroupIds'
     */
    @Test
    public void notifyGroupIdsTest() {
        // TODO: test notifyGroupIds
    }

    /**
     * Test the property 'notifyId'
     */
    @Test
    public void notifyIdTest() {
        // TODO: test notifyId
    }

    /**
     * Test the property 'notifyInterval'
     */
    @Test
    public void notifyIntervalTest() {
        // TODO: test notifyInterval
    }

    /**
     * Test the property 'notifyTypes'
     */
    @Test
    public void notifyTypesTest() {
        // TODO: test notifyTypes
    }

    /**
     * Test the property 'severities'
     */
    @Test
    public void severitiesTest() {
        // TODO: test severities
    }

}
