/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.model;

import org.junit.Test;


/**
 * Model tests for DataRoleCreate
 */
public class DataRoleCreateTest {
    private final DataRoleCreate model = new DataRoleCreate();

    /**
     * Model tests for DataRoleCreate
     */
    @Test
    public void testDataRoleCreate() {
        // TODO: test DataRoleCreate
    }

    /**
     * Test the property 'dataPermissions'
     */
    @Test
    public void dataPermissionsTest() {
        // TODO: test dataPermissions
    }

    /**
     * Test the property 'roleDesc'
     */
    @Test
    public void roleDescTest() {
        // TODO: test roleDesc
    }

    /**
     * Test the property 'roleName'
     */
    @Test
    public void roleNameTest() {
        // TODO: test roleName
    }

}
