/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.model;

import org.junit.Test;


/**
 * Model tests for FunctionRoleCreate
 */
public class FunctionRoleCreateTest {
    private final FunctionRoleCreate model = new FunctionRoleCreate();

    /**
     * Model tests for FunctionRoleCreate
     */
    @Test
    public void testFunctionRoleCreate() {
        // TODO: test FunctionRoleCreate
    }

    /**
     * Test the property 'permissionIdList'
     */
    @Test
    public void permissionIdListTest() {
        // TODO: test permissionIdList
    }

    /**
     * Test the property 'roleDesc'
     */
    @Test
    public void roleDescTest() {
        // TODO: test roleDesc
    }

    /**
     * Test the property 'roleName'
     */
    @Test
    public void roleNameTest() {
        // TODO: test roleName
    }

}
