/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.model;

import org.junit.Test;


/**
 * Model tests for FunctionRoleUpdate
 */
public class FunctionRoleUpdateTest {
    private final FunctionRoleUpdate model = new FunctionRoleUpdate();

    /**
     * Model tests for FunctionRoleUpdate
     */
    @Test
    public void testFunctionRoleUpdate() {
        // TODO: test FunctionRoleUpdate
    }

    /**
     * Test the property 'permissionIdList'
     */
    @Test
    public void permissionIdListTest() {
        // TODO: test permissionIdList
    }

    /**
     * Test the property 'roleDesc'
     */
    @Test
    public void roleDescTest() {
        // TODO: test roleDesc
    }

    /**
     * Test the property 'roleId'
     */
    @Test
    public void roleIdTest() {
        // TODO: test roleId
    }

    /**
     * Test the property 'roleName'
     */
    @Test
    public void roleNameTest() {
        // TODO: test roleName
    }

}
