/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.model;

import org.junit.Test;


/**
 * Model tests for LogBase
 */
public class LogBaseTest {
    private final LogBase model = new LogBase();

    /**
     * Model tests for LogBase
     */
    @Test
    public void testLogBase() {
        // TODO: test LogBase
    }

    /**
     * Test the property 'kvs'
     */
    @Test
    public void kvsTest() {
        // TODO: test kvs
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

}
