/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.model;

import org.junit.Test;


/**
 * Model tests for LogRecord
 */
public class LogRecordTest {
    private final LogRecord model = new LogRecord();

    /**
     * Model tests for LogRecord
     */
    @Test
    public void testLogRecord() {
        // TODO: test LogRecord
    }

    /**
     * Test the property 'collectTime'
     */
    @Test
    public void collectTimeTest() {
        // TODO: test collectTime
    }

    /**
     * Test the property 'contextSeq'
     */
    @Test
    public void contextSeqTest() {
        // TODO: test contextSeq
    }

    /**
     * Test the property 'hostname'
     */
    @Test
    public void hostnameTest() {
        // TODO: test hostname
    }

    /**
     * Test the property 'ip'
     */
    @Test
    public void ipTest() {
        // TODO: test ip
    }

    /**
     * Test the property 'kvs'
     */
    @Test
    public void kvsTest() {
        // TODO: test kvs
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

}
