/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.model;

import org.junit.Test;


/**
 * Model tests for MetricSendParam
 */
public class MetricSendParamTest {
    private final MetricSendParam model = new MetricSendParam();

    /**
     * Model tests for MetricSendParam
     */
    @Test
    public void testMetricSendParam() {
        // TODO: test MetricSendParam
    }

    /**
     * Test the property 'appname'
     */
    @Test
    public void appnameTest() {
        // TODO: test appname
    }

    /**
     * Test the property 'metrics'
     */
    @Test
    public void metricsTest() {
        // TODO: test metrics
    }

}
