/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.model;

import org.junit.Test;


/**
 * Model tests for MetricMetaUpdateParam
 */
public class MetricMetaUpdateParamTest {
    private final MetricMetaUpdateParam model = new MetricMetaUpdateParam();

    /**
     * Model tests for MetricMetaUpdateParam
     */
    @Test
    public void testMetricMetaUpdateParam() {
        // TODO: test MetricMetaUpdateParam
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'metric'
     */
    @Test
    public void metricTest() {
        // TODO: test metric
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'unit'
     */
    @Test
    public void unitTest() {
        // TODO: test unit
    }

}
