/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.model;

import org.junit.Test;


/**
 * Model tests for PagerOfDataIndexVO
 */
public class PagerOfDataIndexVOTest {
    private final PagerOfDataIndexVO model = new PagerOfDataIndexVO();

    /**
     * Model tests for PagerOfDataIndexVO
     */
    @Test
    public void testPagerOfDataIndexVO() {
        // TODO: test PagerOfDataIndexVO
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

}
