/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.model;

import org.junit.Test;


/**
 * Model tests for TenantAddVo
 */
public class TenantAddVoTest {
    private final TenantAddVo model = new TenantAddVo();

    /**
     * Model tests for TenantAddVo
     */
    @Test
    public void testTenantAddVo() {
        // TODO: test TenantAddVo
    }

    /**
     * Test the property 'belongUser'
     */
    @Test
    public void belongUserTest() {
        // TODO: test belongUser
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
