/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.model;

import org.junit.Test;


/**
 * Model tests for TenantVO
 */
public class TenantVOTest {
    private final TenantVO model = new TenantVO();

    /**
     * Model tests for TenantVO
     */
    @Test
    public void testTenantVO() {
        // TODO: test TenantVO
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'tenantName'
     */
    @Test
    public void tenantNameTest() {
        // TODO: test tenantName
    }

}
