/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.model;

import org.junit.Test;


/**
 * Model tests for TenantDetailVO
 */
public class TenantDetailVOTest {
    private final TenantDetailVO model = new TenantDetailVO();

    /**
     * Model tests for TenantDetailVO
     */
    @Test
    public void testTenantDetailVO() {
        // TODO: test TenantDetailVO
    }

    /**
     * Test the property 'belongUser'
     */
    @Test
    public void belongUserTest() {
        // TODO: test belongUser
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'creator'
     */
    @Test
    public void creatorTest() {
        // TODO: test creator
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'tenantName'
     */
    @Test
    public void tenantNameTest() {
        // TODO: test tenantName
    }

}
