/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.model;

import org.junit.Test;


/**
 * Model tests for UserRoleAdd
 */
public class UserRoleAddTest {
    private final UserRoleAdd model = new UserRoleAdd();

    /**
     * Model tests for UserRoleAdd
     */
    @Test
    public void testUserRoleAdd() {
        // TODO: test UserRoleAdd
    }

    /**
     * Test the property 'roleIds'
     */
    @Test
    public void roleIdsTest() {
        // TODO: test roleIds
    }

    /**
     * Test the property 'userIds'
     */
    @Test
    public void userIdsTest() {
        // TODO: test userIds
    }

}
