/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.model;

import org.junit.Test;


/**
 * Model tests for WebAppCreateParam
 */
public class WebAppCreateParamTest {
    private final WebAppCreateParam model = new WebAppCreateParam();

    /**
     * Model tests for WebAppCreateParam
     */
    @Test
    public void testWebAppCreateParam() {
        // TODO: test WebAppCreateParam
    }

    /**
     * Test the property 'appName'
     */
    @Test
    public void appNameTest() {
        // TODO: test appName
    }

    /**
     * Test the property 'siteType'
     */
    @Test
    public void siteTypeTest() {
        // TODO: test siteType
    }

    /**
     * Test the property 'tagSet'
     */
    @Test
    public void tagSetTest() {
        // TODO: test tagSet
    }

}
