/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.auth;

import com.dtsre.acos.sdk.Pair;
import com.dtsre.acos.sdk.ApiException;

import java.net.URI;
import java.util.Map;
import java.util.List;

public interface Authentication {

    /**
     * 鉴权对象
     * @param queryParams 请求参数
     * @param headerParams 请求头
     * @param cookieParams cookie
     * @param payload 请求
     * @param method 方法
     * @param uri url
     * @throws ApiException 异常
     */
    void applyToParams(List<Pair> queryParams, Map<String, String> headerParams, Map<String, String> cookieParams, String payload, String method, URI uri) throws ApiException;

}
