/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.api;

import com.dtsre.acos.sdk.ApiException;
import org.junit.Test;

/**
 * API tests for AlertApi
 */
public class AlertApiTest {

    private final AlertApi api = new AlertApi();

    /**
     * 创建告警规则
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAlertTest() throws ApiException {
        //AlertCreateParam param = null;
        //ROflong response = api.createAlert(param);
        // TODO: test validations
    }

    /**
     * 修改告警规则
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateAlertTest() throws ApiException {
        //AlertUpdateParam param = null;
        //ROfboolean response = api.updateAlert(param);
        // TODO: test validations
    }

}
