/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.api;

import com.dtsre.acos.sdk.ApiException;
import org.junit.Test;

/**
 * API tests for DataIndexApi
 */
public class DataIndexApiTest {

    private final DataIndexApi api = new DataIndexApi();

    /**
     * 创建数据集
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createDataIndexTest() throws ApiException {
        //DataIndexCreateParam param = null;
        //ROflong response = api.createDataIndex(param);
        // TODO: test validations
    }

    /**
     * 删除数据集
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteDataIndexTest() throws ApiException {
        //String id = null;
        //ROfboolean response = api.deleteDataIndex(id);
        // TODO: test validations
    }

    /**
     * 数据集分页查询
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void pageDataIndexTest() throws ApiException {
        //String direction = null;
        //String keyword = null;
        //Integer pageNumber = null;
        //Integer pageSize = null;
        //String sort = null;
        //ROfPagerOfDataIndexVO response = api.pageDataIndex(direction, keyword, pageNumber, pageSize, sort);
        // TODO: test validations
    }

    /**
     * 修改数据集
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateDataIndexTest() throws ApiException {
        //DataIndexUpdateParam param = null;
        //ROfboolean response = api.updateDataIndex(param);
        // TODO: test validations
    }

}
