/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.api;

import com.dtsre.acos.sdk.ApiException;
import com.dtsre.api.v1.client.*;
import com.dtsre.api.v1.client.auth.*;

import org.junit.Test;

/**
 * API tests for TenantApi
 */
public class TenantApiTest {

    private final TenantApi api = new TenantApi();

    /**
     * 创建租户
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTenantTest() throws ApiException {
        //TenantAddVo param = null;
        //ROflong response = api.createTenant(param);
        // TODO: test validations
    }

    /**
     * 获取租户详情
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTenantDetailTest() throws ApiException {
        //Long tenantId = null;
        //ROfTenantDetailVO response = api.getTenantDetail(tenantId);
        // TODO: test validations
    }

    /**
     * 查询所有租户
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listTenantsTest() throws ApiException {
        //ROfListOfTenantVO response = api.listTenants();
        // TODO: test validations
    }

}
