/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.acos.sdk.api;

import com.dtsre.acos.sdk.ApiException;
import org.junit.Test;

/**
 * API tests for UserApi
 */
public class UserApiTest {

    private final UserApi api = new UserApi();

    /**
     * 新增租户的用户
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTenantUserTest() throws ApiException {
        //UserCreate param = null;
        //ROfboolean response = api.createTenantUser(param);
        // TODO: test validations
    }

    /**
     * 删除用户
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUserFromTenantTest() throws ApiException {
        //String userId = null;
        //ROfboolean response = api.deleteUserFromTenant(userId);
        // TODO: test validations
    }

    /**
     * 获取租户下的用户列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUsersFromTenantTest() throws ApiException {
        //Long tenantId = null;
        //Integer pageNum = null;
        //Integer pageSize = null;
        //String searchText = null;
        //ROfPagerOfTenantUserListVo response = api.getUsersFromTenant(tenantId, pageNum, pageSize, searchText);
        // TODO: test validations
    }

    /**
     * 修改用户的基本信息
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUserTest() throws ApiException {
        //UserUpdate param = null;
        //ROfboolean response = api.updateUser(param);
        // TODO: test validations
    }

}
